---
- name: Configure Web Servers
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure the HTTP service is running
      ansible.builtin.systemd:
        name: apache2
        state: started

    - name: Print the HTTP port and max connections
      ansible.builtin.debug:
        msg: "The HTTP port is {{ http_port }} and max connections are {{ max_connections }}"